name: quik
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  get: ^4.7.2
  hugeicons: ^0.0.11
  share_plus: ^11.0.0
  webview_flutter: ^4.11.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/q.png" # Make sure this file exists
  background_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/q.png
